"""
Key Master Configuration Loader.

This module loads the list of trusted executable paths from a JSON file
generated by the installer at a fixed system location.
"""

import json
import logging
from pathlib import Path

# The canonical, system-wide location for the installer-generated config.
_TRUSTED_PATHS_CONFIG_FILE = Path("/etc/auto-secrets/trusted_paths.json")

# Initialize with a safe default.
LEGITIMATE_CLI_PATHS: list[str] = []

if _TRUSTED_PATHS_CONFIG_FILE.exists():
  try:
    # Load the configuration data from the external file.
    config_data = json.loads(_TRUSTED_PATHS_CONFIG_FILE.read_text())

    # We expect a list of strings. Validate the structure.
    paths = config_data.get("trusted_paths")
    if isinstance(paths, list) and all(isinstance(p, str) for p in paths):
      LEGITIMATE_CLI_PATHS = paths
    else:
      # Use logging for when the file is present but malformed.
      logging.getLogger(__name__).error(f"Config file at {_TRUSTED_PATHS_CONFIG_FILE} is malformed.")
  except (json.JSONDecodeError, OSError) as e:
    logging.getLogger(__name__).error(f"Failed to load trusted paths config from {_TRUSTED_PATHS_CONFIG_FILE}: {e}")
